# This workflow executes CI jobs

name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
      - name: Build with USE_SHARED_MEMORY
        run: |
          mkdir -p build
          pushd build
          cmake -DUSE_SHARED_MEMORY=ON ..
          make -j4
          popd
          rm -r build
      - name: Build without USE_SHARED_MEMORY
        run: |
          mkdir -p build
          pushd build
          cmake ..
          make -j4
          popd
          rm -r build
